#!/bin/bash

# Install Homebrew
echo "Installing Homebrew..."
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install Tmux.
echo "Installing Tmux..."
brew install tmux
if [ -f ~/.tmux.conf ]; then
  echo "Removing prevoius Tmux configuration..."
  rm ~/.tmux.conf
fi
ln -n .tmux.conf ~/.tmux.conf
echo "Tmux configured sucessfully."


# BASH CONFIGURATIONS
echo "Configuring bash shell..."

if [ -f ~/.bash_aliases ]; then
  echo "Removing prevoius bash_aliases..."
  rm ~/.bash_aliases
fi
ln -n .bash_aliases ~/.bash_aliases

# Make .bash_profile load .bash_aliases aliases.
echo "# Load aliases form .bash_aliases."
echo "if [ -f ~/.bash_aliases ]; then" >>  ~/.bash_profile
echo ". ~/.bash_aliases" >>  ~/.bash_profile
echo "fi" >>  ~/.bash_profile

echo "Please restart your Mac to apply changes."
